[package]
name = "tauri-plugin-stronghold"
version = "0.1.0"
authors = ["Lucas Nogueira <lucas@tauri.studio>"]
description = "A Tauri plugin for easily interfacing with IOTA Stronghold"
edition = "2018"
exclude = ["/examples", "/webview-dist", "/webview-src", "node_modules"]

[dependencies]
tauri = "0.11"
thiserror = "1.0"
iota-stronghold = { git = "https://github.com/iotaledger/stronghold.rs", branch = "dev" }
riker = { version = "0.4", git = "https://github.com/elenaf9/riker", branch = "master" }
once_cell = "1.5"
serde = "1.0"
serde_json = "1.0"
async-std = { version = "1.9", features = ["attributes"] }
slog = "2.7"
hex = "0.4"

iota-crypto = { git = "https://github.com/iotaledger/crypto.rs", branch = "dev", features = ["hmac", "sha", "pbkdf"] }

[dev-dependencies]
rand = "0.8"
rusty-fork = "0.3"
